spring:
  datasource:
    url: jdbc:mysql://39.107.68.86:3306/novel?characterEncoding=utf-8&useSSL=false
    username: root
    password: 13594859505LW
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 2MB #最大请求文件的大小
      max-file-size: 2MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
server:
  port: 8888
preread:
  #文件上传目录（注意Linux和Windows上的目录结构不同）
  uploadPath: /usr/local/dev/image/



